server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  add_header Content-Security-Policy "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'" always;
  add_header X-Content-Type-Options nosniff always;

  location /api/ {
    proxy_pass http://api:4000;
    proxy_set_header Host $host;
    proxy_set_header X-Request-Id $request_id;
  }

  location /health {
    proxy_pass http://api:4000;
  }
  location /uploads/ {
    proxy_pass http://api:4000;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
